import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next Apps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-3 ">
          <ul className="mb-3 flex justify-center gap-3 alignItems-center">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/About">About</Link></li>
          </ul>
          <hr/>
        </nav>
        {children}
        </body>
    </html>
  )
}
